package com.web.jim;
// Generated Nov 25, 2016 7:13:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductCode generated by hbm2java
 */
public class ProductCode  implements java.io.Serializable {


     private String prodCode;
     private char discountCode;
     private String description;
     private Set<Product> products = new HashSet<Product>(0);

    public ProductCode() {
    }

	
    public ProductCode(String prodCode, char discountCode) {
        this.prodCode = prodCode;
        this.discountCode = discountCode;
    }
    public ProductCode(String prodCode, char discountCode, String description, Set<Product> products) {
       this.prodCode = prodCode;
       this.discountCode = discountCode;
       this.description = description;
       this.products = products;
    }
   
    public String getProdCode() {
        return this.prodCode;
    }
    
    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }
    public char getDiscountCode() {
        return this.discountCode;
    }
    
    public void setDiscountCode(char discountCode) {
        this.discountCode = discountCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


